# Generated by Django 4.2.18 on 2025-01-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='make_changes',
            new_name='time_stamp',
        ),
    ]
