# Generated by Django 4.2.18 on 2025-02-08 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_make_changes_equipment_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
